### ISSUE TITLE
Are there other expressions than wildcard *?

### ISSUE THREAD

**Issue by baflo** [DannyBen/completely#30]
I was wondering if there are other options to create generic patterns, e.g.:

```
mygit:
- --help
- --version
- status
- init
- commit

mygit (status|commit|init):
- --help
```

**Comment by DannyBen** [comment]
Well, no. The asterisk is getting a special treatment here:

https://github.com/DannyBen/completely/blob/42fb4a1aebcae917af8b3ec72407039c92875b47/lib/completely/pattern.rb#L33-L41

However, you can easily achieve a similar DRY approach, by using YAML anchors:

```yaml
mygit status: &common
- --help
- --verbose
- --branch

mygit commit: *common
mygit init: *common
```
