### ISSUE TITLE
Completion for command --option=value

### ISSUE THREAD

**Issue by misaflo** [DannyBen/completely#42]
Hi,

Thanks for this nice project.

I try to have completion for `my_command --option=value`.

I have tested this:

```yaml
my_command:
- do-this
- do-that
- --output-format=

my_command --output-format:
- text
- csv
- json
- xml

my_command do-this:
- ''

my_command do-that:
- ''
```

`my_command --<TAB><TAB>` put a space after `=`: `my_command --output-format=
`, and there is no more completion for `do-this` and `do-that`.

I also try this :

```yaml
my_command:
- do-this
- do-that
- --output-format=text
- --output-format=csv
- --output-format=json
- --output-format=xml

my_command do-this:
- ''

my_command do-that:
- ''
```

There is no space, but the completion stop after `--output-format=`.

Is it possible do have completion for `command --option=value`?

**Comment by DannyBen** [comment]
No. I don't believe is.
The completion script generated by completely is simplified, it will never be able to do what a full blown completion script does.

The original intention of this gem, was to provide you all the available completions for a given command, regardless of order.

For example, if you run `completely init` you will get a starting point showing this intention. A snippet from it:

```yaml
mygit status:
- --help
- --verbose
- --branch
- $(git branch 2> /dev/null)
```

Notice that in this case, running `mygit status <tab>` will show branches, even if they are only intended to appear after `--branch` (of course, in this hypothetical "git" example).

Now - if you insist on limiting some arguments to a flag, you still can, you just need to use a wildcard where "other flags" can appear. See [this section in the README](https://github.com/DannyBen/completely/#suggesting-flag-arguments).

And finally, in case you are not familiar with it - there is a `completely test` command that lets you test completions of your YAML, without generating anything.

```
$ completely test "mygit status "
$ completely test "mygit status --bra"
$ completely test "mygit status --branch "
```

note the trailing space in some cases, denoting you "moved on" to the next word.

**Comment by DannyBen** [comment]
Found one way of doing it, although I am not sure it is suitable for your use case:

```yaml
mygit:
- --help
- --verbose
- --branch

# this is for allowing without '='
- --env

- --env=production
- --env=development

# this is for completing '--env <tab>' with space
mygit*--env:
- production
- development
```
