### ISSUE TITLE
handle positional arguments

### ISSUE THREAD

**Issue by brammeleman** [DannyBen/completely#49]
I have some shell scripts that have positional arguments. It does not look like `completely` support this?

Could look like:
```
command [--anoption] [--exclude_file <file>] <path> <group> [extragroup]
```

```yml
command:
- --anoption
- --exclude_file
command*--exclude_file:
- <file>
command*1:
- <file>
- <dir>
command*2:
- <group>
command?3:
- <group>
```

**Comment by DannyBen** [comment]
1. In general, completely does not handle complex conditions or positions. Generating a script that does that from a simple configuration file is not realistic.
2. If you can express the input pattern as a string with a potential wildcard (`*`), then you can provide a list of options for that pattern.
3. Using your example as reference - it is common to allow flags both before or after the positional arguments:
   `command [options] <path> <group>` and `command <path> <group> [options]`
   so your ask becomes even more complex to handle.

I would suggest to simply do something like this:

```yaml
command:
- --anoption
- --exclude_file
- <file>
- <directory>
- <group>

command*--exclude_file:
- <file>
```
