### ISSUE TITLE
Question: is it possible to not match unknown patterns?

### ISSUE THREAD

**Issue by karthik2804** [DannyBen/completely#62]
I am attempting to create completions for a program that can run plugins. The plugins in these cases are external binaries for which I do not have information about their arguments. Is there a way to define not to suggest any completion in case of unknown patterns? 

A small example would be 

```yaml
my_cmd:
- plugins
- $(my_cmd plugins list)

my_cmd plugin:
- list
```

In the case above, I would like for completion to work for `my_cmd plugins <TAB>` and show me the `list` subcommand. But when I type `my_cmd my_plugin` where `my_plugin` is an external binary, nothing shows up. Is that possible?
