### ISSUE TITLE
Feature request: support multi-level yaml

### ISSUE THREAD

**Issue by vkkodali** [DannyBen/completely#74]
If I understand correctly, multilevel yamls are not supported currently. 
For example, I would like to do the following: 
```yaml
appname:
- -input:
  - <file>
``` 

instead of doing:
```yaml
appname:
- -input

appname -input:
- <file>
```

Is that something you would be able to implement?

**Comment by DannyBen** [comment]
Well, it is a good idea of course.
However, this complicates things to a point where the YAML becomes much less readable.

If I take the example YAML from the README, and nest it, it might look like this:

```yaml
mygit:
  --help:
  --version:
  status:
    --help:
    --verbose:
    --branch:
    $(git branch 2>/dev/null):
  init:
    --bare:
    <directory>:
  commit:
    <file>:
    --help:
    --message:
    --all:
    -a:
    --quiet:
    -q:
  checkout:
    "*--branch":  &branches
      - $(git branch 2>/dev/null)
    "*-b": *branches
```

Note the last `checkout` node - where flags in this case (`--branch`), need to be prefixed with `*`.

I wonder if we should consider replacing YAML with a simple indented file, like this:

```
mygit
  --help -h
  --version -v
  status
    --help -h
    --verbose
    --branch
    $(git branch 2>/dev/null)
  init
    --bare
    <directory>
  checkout
    * --branch -b
      $(git branch 2>/dev/null)
```

**Comment by DannyBen** [comment]
How do you feel about this format?

```yaml
mygit:
- --help
- --version
- init:
  - --bare
  - <directory>
- checkout:
  - +--force
  - +--branch: &branches
    - $(git branch --format='%(refname:short)' 2>/dev/null)
  - +-b: *branches
```

which looks like this in the "flat" format:

```yaml
mygit:
- "--help"
- "--version"
- init
- checkout
mygit init:
- "--bare"
- "<directory>"
mygit checkout:
- "+--force"
- "+--branch"
- "+-b"
mygit checkout*--branch:
- "$(git branch --format='%(refname:short)' 2>/dev/null)"
mygit checkout*-b:
- "$(git branch --format='%(refname:short)' 2>/dev/null)"
```

Note the use of `+` as an alternative to `*`, since YAML has a special meaning for `*` in keys.

```yaml
# this...
- checkout:
  - "*--force"

# ... can be written like this (note no quotes, which is prettier)
- checkout:
  - +--force
```

Also need to note that this "flattener" I created, treats strings that start with `+` or `*` differently, by merging them with the previous prefix **without sapce**:

```yaml
mygit checkout*--branch

# instead of

mygit checkout *--branch
```

Since this is a standalone converting class - I believe I can make it work, and still support the current flat format.

Thoughts?
