### ISSUE TITLE
option to define `-o nosort` to complete command

### ISSUE THREAD

**Issue by dxlr8r** [DannyBen/completely#77]
As the title says. By default the completion is sorted, but I do my own custom sorting, so I do not want that reversed.

**Comment by DannyBen** [comment]
Do you mean you want the ability to change this output:

```
complete -F _mygit_completions mygit
```

to this:

```
complete -F _mygit_completions -o nosort mygit
```

If so - I wonder if this feature should be made more generic, like to allow adding *any* option (any `-o` option), or perhaps even, to add *anything* here:   `complete -F _function_name (user added line here) binary_name`

Thoughts?

**Comment by dxlr8r** [comment]
Yes, that is what I meant.

Sounds like a good approach, other might want others options than just nosort.

**Comment by DannyBen** [comment]
And how should the user specify these options? Perhaps a special key in the YAML for this and future options?

```yaml
# completely.yaml
completely_options:
  complete_options: -o nosort

# ... rest of the completions list
```
